os: osx
osx_image: xcode8
sudo: false
language: objective-c

branches:
  only:
  - staging
  - integration
  
env:
  - NODE_VERSION="6" NPM_VERSION="3" TNS_VERSION="rc"

env:
  global:
    - APP_NAME="tnswebformclient"
    - 'DEVELOPER_NAME="iPhone Distribution: Khor Yong Hao (C4F7EVGZVS)"'
    - PROFILE_NAME="tnswebformprofile2018"
    - NODE_VERSION="6" NPM_VERSION="3" TNS_VERSION="rc"
    - 'CODE_SIGN_IDENTITY="iPhone Distribution: Khor Yong Hao (C4F7EVGZVS)"'
    - PROVISIONING_PROFILE="6d0074e8-3158-43ce-bf88-9130eab30362"
    - DEVELOPMENT_TEAM="C4F7EVGZVS"
    - 'XCBUILD_SAFE_SH="/Users/travis/build/fyhao/tns-webform-client/scripts/xcbuild-safe.sh"'

script:
  - echo "Travis script"
  - ./scripts/script.sh

before_script:
- echo "Travis before_script"
- ./scripts/before-script.sh
  
before_install:
  - echo "Travis before_install"
  - chmod +x ./scripts/*.sh
  - ./scripts/before-install.sh

after_success:
  - echo "Travis after_success"
  - ./scripts/after-success.sh
  
  
after_script:
- echo "Travis after_script"
- ./scripts/after-script.sh


