language: node_js
branches:
  only:
  - staging
  
language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

install:
    - wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
    - npm install -g nativescript.tgz --ignore-scripts
    - tns usage-reporting disable
    - tns error-reporting disable
    - npm install
    
    
script:
    - npm run tslint
    - tns build android